### ISSUE TITLE
myManga successor?

### ISSUE THREAD

**Issue by olinWong** [jrjparks/manga-broker#1]
Is this the successor to myManga?
Really liked the myManga UI/functionality - mostly just issues with bad sources.
If this is the "v2": are you making the switch for more robust scraping? (Ex: I see that cloudkicker)

**Comment by jrjparks** [comment]
You betcha, although this is just the scrappers. I'm moving to NodeJS and Electron to make a cross-platform app. The main advantage to this change is with some sources starting to use CloudFront JavaScript evaluation is easy.
